import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarPage from "./navbar/page";
import FooterPage from "./footer/page";
import NewsletterPage from "./newsletter/page";
import GSAPInitializer from "@/component/gsap/GSAPInitializer";
import { Analytics } from "@vercel/analytics/react"; // ✅ Add this line

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <GSAPInitializer /> {/* ✅ Runs on client */}
        <NavbarPage />
        {children}
        <NewsletterPage />
        <FooterPage />
        <Analytics /> {/* ✅ Add this at the bottom of body */}
      </body>
    </html>
  );
}
